base: http://files.travis-ci.org/boxes/bases/oneiric32_base.box
json:
  rvm:
    default: 1.9.2
    rubies:
    - name: 1.9.2
    gems:
      - bundler
      - rake
      - chef
  mysql:
    server_root_password: ""
  postgresql:
    max_connections: 256
  travis_build_environment:
    use_tmpfs_for_builds: false
recipes:
  #
  # Travis environment + build toolchain
  #
  - travis_build_environment
  - apt
  - build-essential
  - networking_basic
  - openssl
  - sysctl
  - git
  - mercurial
  - scons
  - unarchivers
  #
  # additional libraries needed to run headless WebKit,
  # build parsers, for ossp-uuid to work and so on
  #
  - libqt4
  - libgdbm
  - libncurses
  - libossp-uuid
  - libffi
  - ragel
  - imagemagick
  - mingw32
  #
  # JDK and related build toolchain
  #
  - java
  - ant
  - maven3
  - leiningen
  - sbt
  - gradle::tarball
  - golang
  #
  # Ruby via RVM (default Debian installations are secure at the cost of
  # being unusable without PATH tweaking, for our VMs we can just go with RVM.
  # This includes rubygems, bundler and rake.
  #
  - rvm
  - rvm::multi
  #
  # Python and pip
  #
  - python
  - python::pip
  #
  # Node.js
  #
  - nodejs::multi
  #
  # Data stores
  #
  - sqlite
  - postgresql::client
  - mysql::client
  - mysql::server_on_ramfs
  - postgresql::server_on_ramfs
  - redis
  - riak
  - mongodb
  - couchdb::ppa
  - memcached
  - neo4j-server::tarball
  - cassandra::datastax
  - firebird
  #
  # Messaging
  #
  - rabbitmq::with_management_plugin
  - zeromq
  #
  # Search
  #
  - elasticsearch
  - sphinx::all
  #
  # Headless WebKit, browsers, Selenium toolchain, etc
  #
  - xserver
  - firefox
  - chromium
  - phantomjs::tarball
  #
  # Debugging & support
  #
  - emacs::nox
  - vim
  - sweeper
